matrix:
  include:
  - language: node_js
    node_js:
      - "node"
    script:
      - docker build -t blog-frontend .

  - language: node_js
    node_js:
      - "node"
    addons:
      sonarcloud:
        organization: martinheinz-github
        token:
          secure: "qglaIlxCS3KjHwaBzpL/rDG0/vwlDzH9NhAEfIUi9LdWn7zfq43UCLZfH35oQ5Xwj1E/lrw3aZ3CCXW4zzGQcK46FbaUk5ls2gKFjvkCMv0X6oMVUsFN1wjsRg43fJl5k3QD5OE8BN5F2jU6IC5fejAI8Pm19ytSC5VpsN86D/Ju7VddODEL2BgkBxeqGC37SbMhlhGBD5D8zw+FaSiy4bDaTbvS7VNruzvKi62f8n/geSTgbGwwtck2U5s7SR6DTz4oim/dbkx+b3PLNhe9+bmaZyFqy8wUPm0cduS6SI9VrWRxd9TbQkRXqmfhliDFv5NetH2oJahstsbGML5pvR1NxJmJjK+kjcInx0Cv2mbwkPWLM0UL6EKPg0+UNgTMXyAhftqpoF7CkFKPxSPWP0ES4CoUo9kLrUA+h/Vx72bF0czzeOrbnWQUJchHwqj+jiCLlVqE/Z6/dDt1O9tTgHdAGw6HOqXWOK6OmAjqXK3KOw+eWkHv/IzpEPNzYIrUgggwmEn8leGgezFGMOtqPzHuQefRimR0WqBE6qNrjGy8ASZ3ws1JxRWrMH3RXgg+G2nqptuAjEWLAXM+znZq4sTHDi1ToIhVAxXb3cg767gs+Rd6LM43QFmlDyuqAMS4VdNf983nHSbYAaDtpoEQRxV08MZ6DrqAV5/nJatXroI="
    script:
      - npm run test:unit
      - sonar-scanner

  - language: node_js
    node_js:
      - "node"
    addons:
      code_climate:
        repo_token:
          secure: "n7fZlCX2FQUqBVhiULGSVY+7LHpkjDOg7SL233fGHMcdhz/6vKMX1no89LZ7aEPFAialiPZdUyRMYe/rC4tNZISJcfL71hchvWyXQ2b0K6MUD2LPTyUQKeoht5donYFooZJBhCQJ8mAnSXDmOf3EzsccFB3xAaAmOwOh5VI0hZ/GVyKSnqjojEmJL8O3aXKb6hYjPnct5XrbFwUifCELh/gfSzYdVr71rUnJcLhGjTvsbORhoFCCphSR5KpKA2CrgcA5VzAA1yN+ZupKxAqFk4XdABQpNsvHKjm5mDx1jDBLsRSWd1s5+3pPl3AlhpLN8xOz0gagxBWKSIOmVq9qCtDIp1sZKwNg6daeSCKON4Kfz4K+c4c35AqlgEUfT9mg23y0AZLj3gWisifVGJsoHtN2EaJBaBsLWeF9Vd1C6/2k9zomgfpkPQTsC9e05U3odT20eJPpTT9X8TufO3W6kGiBq56TgDMs8VmPXMKL/px4dWoCwyjtvfpTHOn3nCzs8gSFbpwDa8E5pgO73x8aMV+1VkYQuIe0dpk0J2x4+vcyIR5WVfOjDUrRXgYbslRR0RFRTySvfvNLzNnjdc4rFDK8maECiCVANlDd55NJ3lO7G42b3tPcmD/sUDRKEz3xnlEKcPQDggLSRZLzT60bpN2Fig4sz59ADZ6ldmTe9vc="

    script:
      - npm run test:unit

    after_script:
      - codeclimate < ./coverage/lcov.info

notifications:
  email: false
