matrix:
  include:
  - language: node_js
    node_js:
      - "node"
    script:
      - docker build -t blog-frontend .

  - language: node_js
    node_js:
      - "node"
    addons:
      sonarcloud:
        organization: martinheinz-github
        token:
          secure: "qglaIlxCS3KjHwaBzpL/rDG0/vwlDzH9NhAEfIUi9LdWn7zfq43UCLZfH35oQ5Xwj1E/lrw3aZ3CCXW4zzGQcK46FbaUk5ls2gKFjvkCMv0X6oMVUsFN1wjsRg43fJl5k3QD5OE8BN5F2jU6IC5fejAI8Pm19ytSC5VpsN86D/Ju7VddODEL2BgkBxeqGC37SbMhlhGBD5D8zw+FaSiy4bDaTbvS7VNruzvKi62f8n/geSTgbGwwtck2U5s7SR6DTz4oim/dbkx+b3PLNhe9+bmaZyFqy8wUPm0cduS6SI9VrWRxd9TbQkRXqmfhliDFv5NetH2oJahstsbGML5pvR1NxJmJjK+kjcInx0Cv2mbwkPWLM0UL6EKPg0+UNgTMXyAhftqpoF7CkFKPxSPWP0ES4CoUo9kLrUA+h/Vx72bF0czzeOrbnWQUJchHwqj+jiCLlVqE/Z6/dDt1O9tTgHdAGw6HOqXWOK6OmAjqXK3KOw+eWkHv/IzpEPNzYIrUgggwmEn8leGgezFGMOtqPzHuQefRimR0WqBE6qNrjGy8ASZ3ws1JxRWrMH3RXgg+G2nqptuAjEWLAXM+znZq4sTHDi1ToIhVAxXb3cg767gs+Rd6LM43QFmlDyuqAMS4VdNf983nHSbYAaDtpoEQRxV08MZ6DrqAV5/nJatXroI="
    before_script:
    - docker build -t blog-frontend .
    - echo "Run tests inside docker image."
    - echo "Save reports generated by image to host."
    script:
    - sonar-scanner

notifications:
  email: false
